name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-publish-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      # Not need it here as we do not have dependencies
      # - name: Install dependencies
      #   run: npm ci

      - name: Build
        run: npm run build

      - name: Check version
        id: check
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          PUBLISHED_VERSION=$(npm view $PACKAGE_NAME version 2>/dev/null || echo "0.0.0")
          echo "Current version: $CURRENT_VERSION"
          echo "Published version: $PUBLISHED_VERSION"
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          if [ "$CURRENT_VERSION" != "$PUBLISHED_VERSION" ]; then
            echo "New version detected: $CURRENT_VERSION"
            echo "new_version=true" >> $GITHUB_OUTPUT
          else
            echo "Version unchanged: $CURRENT_VERSION"
            echo "new_version=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish to npm
        if: steps.check.outputs.new_version == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Check if version exists in R2
        id: version_check
        env:
          R2_ENDPOINT: https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
          BUCKET_NAME: boversauros-tokens
        run: |
          VERSION_EXISTS=$(aws s3api list-objects --bucket $BUCKET_NAME --prefix "${{ steps.check.outputs.version }}/" --endpoint-url $R2_ENDPOINT --max-items 1 --query 'Contents[0].Key' --output text)
          if [ "$VERSION_EXISTS" != "None" ] && [ -n "$VERSION_EXISTS" ]; then
            echo "Version folder already exists in R2"
            echo "version_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Version folder does not exist in R2"
            echo "version_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS CLI for R2
        if: steps.version_check.outputs.version_exists == 'false'
        run: |
          mkdir -p ~/.aws
          echo "[default]
          aws_access_key_id = ${{ secrets.R2_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.R2_SECRET_ACCESS_KEY }}" > ~/.aws/credentials
          echo "[default]
          region = auto" > ~/.aws/config
  
      - name: Deploy to R2
        if: steps.version_check.outputs.version_exists == 'false'
        env:
          R2_ENDPOINT: https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
          BUCKET_NAME: boversauros-tokens
        run: |
          echo "Current version: ${{ steps.check.outputs.version }}"
          echo "Uploading build files to R2..."
          aws s3 sync ./dist s3://$BUCKET_NAME/${{ steps.check.outputs.version }} --endpoint-url $R2_ENDPOINT
          aws s3 sync ./dist s3://$BUCKET_NAME/latest --endpoint-url $R2_ENDPOINT
          
          echo "Listing uploaded files in version-specific folder:"
          aws s3 ls s3://$BUCKET_NAME/${{ steps.check.outputs.version }} --recursive --endpoint-url $R2_ENDPOINT
          
          echo "Listing uploaded files in latest folder:"
          aws s3 ls s3://$BUCKET_NAME/latest --recursive --endpoint-url $R2_ENDPOINT
          
          echo "Done!"
  
      - name: Output R2 URLs
        if: steps.version_check.outputs.version_exists == 'false'
        run: |
          echo "Your CSS files are now available at:"
          echo "Latest version: https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com/$BUCKET_NAME/latest/your-css-file.css"
          echo "Specific version: https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com/$BUCKET_NAME/${{ steps.check.outputs.version }}/your-css-file.css"
          echo "Replace 'your-css-file.css' with the actual name of your CSS file."