name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-publish-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      # Not need it here as we do not have dependencies
      # - name: Install dependencies
      #   run: npm ci

      - name: Build
        run: npm run build

      - name: Check version
        id: check
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          PUBLISHED_VERSION=$(npm view $PACKAGE_NAME version || echo "0.0.0")
          if [ "$CURRENT_VERSION" != "$PUBLISHED_VERSION" ]; then
            echo "New version detected: $CURRENT_VERSION"
            echo "::set-output name=new_version::true"
            echo "::set-output name=version::$CURRENT_VERSION"
          else
            echo "Version unchanged: $CURRENT_VERSION"
            echo "::set-output name=new_version::false"
          fi

      - name: Publish to npm
        if: steps.check.outputs.new_version == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install rclone
        run: sudo -v ; curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "[r2]
          type = s3
          provider = Cloudflare
          account = ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          key = ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
          endpoint = https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com" > ~/.config/rclone/rclone.conf

      - name: Test R2 Connection
        run: |
          echo "Testing R2 connection..."
          rclone lsd r2:
          echo "Listing boversauros-tokens bucket..."
          rclone lsd r2:boversauros-tokens || echo "Failed to list bucket"

      # - name: Upload to R2
      #   run: |
      #     VERSION=${{ steps.check.outputs.version }}
      #     rclone sync ./dist r2:boversauros-tokens/$VERSION
      #     rclone sync ./dist r2:boversauros-tokens/latest